version: '3.4'

services:
  management-service-command:
    build: ./management-service-command

    ports:
      - "8003:8003"

    restart: always

  management-service-query:
    build: ./management-service-query

    ports:
      - "8004:8004"

    restart: always
